name: Run Unit Test Case
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run test cases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          cd src/tests
          python -m pip install --upgrade pip
          pip install coverage
          pip install pytest
        working-directory: ./Demo-Repo-for-actions

      - name: check folder
        run: pwd
        working-directory: ./Demo-Repo-for-actions/src/tests

      - name: Run Unit Tests
        run: |
          coverage run -m pytest tests/
        working-directory: ./Demo-Repo-for-actions/src/tests
