name: Run Unit Test Case
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run test cases
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Debug directory contents
        run: ls -R
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage
          pip install pytest
      - name: Run Unit Tests
        run: |
          coverage run -m pytest https://github.com/CoderApple/Demo-Repo-for-actions/tree/main/src/tests



