name: Run Unit Test Case
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run test cases
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage
          pip install pytest
      - name: Change working directory to src/tests
        working-directory: ./Demo-Repo-for-actions
        run: cd src/tests
      - name: check folder
        run: pwd
      - name: Run Unit Tests
        run: |
          coverage run -m pytest tests/
