name: Run Unit Test Case
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run test cases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage
          pip install pytest

      - name: check folder
        run: |
         cd src/tests/
         pwd
         coverage run -m pytest test_math_operations.py test_employee_details.py
         continue-on-error: true

      - name: Check test results
        run: |
          if [ $? -eq 0 ]; then
            echo "Tests passed, building Docker image..."
            docker build -t charanb2001/your_image_name .
            docker push charanb2001/your_image_name
          else
            echo "Tests failed, not building Docker image."
          fi
        env:
          DOCKER_USERNAME: ${{ secrets.charanb2001 }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

